const database = {
  services: [
    {
      id: crypto.randomUUID().toString(),
      image1: "webDevelopment.png",
      image2: "oneIcon.png",
      icon: "arrow.png",
      title: "Web Development",
      description: `Lorem ipsum dolor sit amet, consete sadipscing elitr, sed di nonumy eirm tempor invidunt dolore.`,
      bgColor: "hsla(274, 78%, 62%, 0.3)",
    },
    {
      id: crypto.randomUUID().toString(),
      image1: "mobileDevelopment.png",
      image2: "twoIcon.png",
      icon: "arrow.png",
      title: "Mobile Development",
      description: `Lorem ipsum dolor sit amet, consete sadipscing elitr, sed di nonumy eirm tempor invidunt dolore.`,
      bgColor: "hsla(186, 100%, 67%, 0.3)",
    },
    {
      id: crypto.randomUUID().toString(),
      image1: "uiUx.png",
      image2: "threeIcon.png",
      icon: "arrow.png",
      title: "UI/UX Design",
      description: `Lorem ipsum dolor sit amet, consete sadipscing elitr, sed di nonumy eirm tempor invidunt dolore.`,
      bgColor: "hsla(234, 100%, 61%, 0.3)",
    },
  ],
  teams: [
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
    {
      id: crypto.randomUUID().toString(),
      surname: "Natia Okropiridze",
      position: "Front End Developer",
      image: "teamPerson.png",
    },
  ],
};
export default database;
